version: '3'
services:
  # PHP Service
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: akashic
    env_file: ./server/.env
    container_name: akashic_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  # Personal Service
  nextjs:
    build:
      context: ./clients/personal
      dockerfile: Dockerfile
    image: personal
    container_name: personal
    restart: unless-stopped
    ports:
      - "3006:3000"
    networks:
      - app-network
    command: ["pnpm", "run", "dev"]

  # Nginx Service
  webserver:
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    image: nginx:alpine
    container_name: akashic_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3005:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
